version: '3.8'

services:
  jupyterlab:
    build: 
      dockerfile: tverous-extension.dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/workspace/notebooks
    environment:
      - JUPYTER_TOKEN=passwd
